// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfd2y5n1xKzkY3OjXxzJK99uz8aWpIbcQ',
    appId: '1:969596291373:web:1ee961b6a186eed47e6ba4',
    messagingSenderId: '969596291373',
    projectId: 'lovebee-d89b0',
    authDomain: 'lovebee-d89b0.firebaseapp.com',
    databaseURL: 'https://lovebee-d89b0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lovebee-d89b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3WupdmkjLlH9b2NegcdXP_hL56HBzz9w',
    appId: '1:969596291373:android:ee19c7abce138f787e6ba4',
    messagingSenderId: '969596291373',
    projectId: 'lovebee-d89b0',
    databaseURL: 'https://lovebee-d89b0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lovebee-d89b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqgsqnaIsQm8ndvECOCAB1xVHzrrgFrA',
    appId: '1:969596291373:ios:05dd1760326e402c7e6ba4',
    messagingSenderId: '969596291373',
    projectId: 'lovebee-d89b0',
    databaseURL: 'https://lovebee-d89b0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lovebee-d89b0.firebasestorage.app',
    androidClientId: '969596291373-5j3urvuof94ddvre7bcnljkl9b0m0kgh.apps.googleusercontent.com',
    iosClientId: '969596291373-em41ifobt6l4q1s65oeu18ubd5gkhf4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.lovebee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdqgsqnaIsQm8ndvECOCAB1xVHzrrgFrA',
    appId: '1:969596291373:ios:05dd1760326e402c7e6ba4',
    messagingSenderId: '969596291373',
    projectId: 'lovebee-d89b0',
    databaseURL: 'https://lovebee-d89b0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lovebee-d89b0.firebasestorage.app',
    androidClientId: '969596291373-5j3urvuof94ddvre7bcnljkl9b0m0kgh.apps.googleusercontent.com',
    iosClientId: '969596291373-em41ifobt6l4q1s65oeu18ubd5gkhf4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.lovebee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfd2y5n1xKzkY3OjXxzJK99uz8aWpIbcQ',
    appId: '1:969596291373:web:1ee961b6a186eed47e6ba4',
    messagingSenderId: '969596291373',
    projectId: 'lovebee-d89b0',
    authDomain: 'lovebee-d89b0.firebaseapp.com',
    databaseURL: 'https://lovebee-d89b0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lovebee-d89b0.firebasestorage.app',
  );
}
